language: python
python:
  - "3.5"

cache: pip

addons:
  postgresql: "9.3"

install:
  - pip install -r requirements.txt --quiet
  - pip install coveralls

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - python manage.py migrate
  - python manage.py test
  - coverage run --source=emotion manage.py test emotion

after_success:
  - coveralls
